### ISSUE TITLE
Adding Developer Portal//Documentation

### ISSUE THREAD

**Issue by xcantera** [XDC-Community/XDC-Community.github.io#15]
https://howto.xinfin.org/

Would we add something like this https://howto.xinfin.org/ or a gitbook. Will be so much easier write here than write on HTML code.

**Comment by Tpada13** [comment]
Our main focus was a seamless user experience for the developer portals with expansion to allow for features beyond documentation.  A Jekyll template on GitHub pages provides the balance we were looking for.  With that said, using Gitbooks for documentation will admittedly make it easier for the community to contribute, and therefore we are going to restructure to continue to use GitHub pages for the static xdc.community, but will link to Gitbooks for documentation.
Great recommendation!
Thank you.

**Comment by WalterBlueu** [comment]
@xcantera I am re-opening this issue so that you can close it out once you feel it has been properly addressed.
