### ISSUE TITLE
discord invite link has expired

### ISSUE THREAD

**Issue by inv4fee2020** [XDC-Community/XDC-Community.github.io#2]
https://github.com/XDC-Community/XDC-Community.github.io/blob/974672a01a970dba856abf5aa5629e922378fcc2/_config.yml#L28

**Comment by cryptoRREN** [comment]
> https://github.com/XDC-Community/XDC-Community.github.io/blob/974672a01a970dba856abf5aa5629e922378fcc2/_config.yml#L28

Here is a new link that will not expire. Thank you
https://discord.gg/MFeHJ6C5gn

**Comment by WalterBlueu** [comment]
Thank you for flagging this!  I will get this fixed and post back.

**Comment by WalterBlueu** [comment]
@inv4fee2020 This issue has been resolved.  Please verify and close it out at your leisure.

**Comment by inv4fee2020** [comment]
verified working. thx.
