### ISSUE TITLE
invalid "Docs" link on main page slider

### ISSUE THREAD

**Issue by inv4fee2020** [XDC-Community/XDC-Community.github.io#3]
Link references doxy' main site rather than the actual "Docs" section of the site

https://github.com/XDC-Community/XDC-Community.github.io/blob/dac1730832db62ccb7d83adb183cabd6b9c17489/_data/slider.yml#L4

**Comment by WalterBlueu** [comment]
Thank you for reporting this, I just updated the link to point to the correct page.  I am planning to have all of the template pages/links/content removed by the end of this week.

Please review and close out at your leisure.
